### ISSUE TITLE
List of active ingredients

### ISSUE THREAD

**Issue by REFAEI91** [REFAEI91/capstone-project#1]
## Value proposition

As a user
I want to see all active ingredients in order to get an overview of all ingredients

## Description
![US 1](https://user-images.githubusercontent.com/56527662/235963028-a99ff31d-f073-4070-80f9-50f653f13d34.png)

## Acceptance criteria

- [x] Each ingredient has a diffrent card .
- [x] the name of each ingredient is displayed in the upper left corner of the card
- [x] The List scrolls vertically.

## Tasks

- [x]  Create  a branch 
- [x]  Global Styles 
- [x]  Components/Card
- [x]  Components/Header
- [x]  Create a db.js with "active ingredients"

Size:

**Comment by mbosselmann** [comment]
Hi Refaei,
great work! 💪 I have some remarks for you to consider before moving further:

## Value Proposition
- in order to get a better understanding of the purpose of your user story, I would recommend to write "I want to see all active ingredients in order to get an overview of all ingredients" instead of "in order to read it"

## Description
- I like your wireframe, but the size is somehow really large. Maybe you can scale it down? If the text is then not readable, maybe you can choose a different text size for your wireframe? 🤔 

## Acceptance Criteria
- "The name of ingredient shows on top right of every Card." I think you mean "the name of each ingredient is displayed in the upper left corner of the card"? 🤔 
- not only the title of your app, but also the icon is also always visible or? I would refer to the icon too.

## Tasks
- "Compnents/Card." Just if you copy thie later for other user stories: One "o" is missing in "Components"
- "Create a db.js with "Activ ingredient" - also for naming purposes: I think you mean "active ingredients" or?
- and you do not to end with "." after each task :)

And if you do not want to set a size for your user story (this is optional) then you can remove this part. With size you can decide what you think is the complexity of your user story (usually small, medium or large).

I hope this does help! Feel free to ask if you have questions. :)

**Comment by mbosselmann** [comment]
Hi Refaei,
you rock! 🪨  I only have one point left: In your wireframe the text for each ingredient is now really hard to read. It would be cool if you can fix this by choosing a different text size in excalidraw. Please try to find a solution (I already have your future user stories in mind where this problem might arise too.). 👀 

But everything else looks good. Therefore I will approve your first user story! 🥳

**Comment by frank12421** [comment]
Hi Refai, LGTM!
