### ISSUE TITLE
Add toggle button for "More Info" and  "Less Info" on cards

### ISSUE THREAD

**Issue by REFAEI91** [REFAEI91/capstone-project#2]
## Value proposition

As a user
I want to view more information (Uses , Dosage , Side effect , and Precautions ) about a card and
 easily switch back to the summary view.

## Description

![US 2](https://user-images.githubusercontent.com/56527662/235954050-887d5c60-bed0-41a2-a614-38dce3a9e85c.png)

## Acceptance criteria

- [x] Each card should have a toggle button for "More Info" and "Less Info" in the right Bottom.
- [x] When the user clicks the "More Info" button, the card should expand to display additional details (Uses , Dosage , Side effect , and Precautions ).
- [x] When the user clicks the "Less Info" button, the card should collapse to display only the summary.
- [x] The expanded card should display the card's title,Uses , Dosage , Side effect , and Precautions .
- [x] The toggle buttons should be clearly labeled and easy to use.

## Tasks
- [x] Create  a branch .
- [x] Design the user interface for the toggle button and the expanded card view.
- [x] Implement the functionality to toggle between the summary and expanded card views.
- [x] Populate the expanded card view with the relevant card information.
- [x] Test the feature to ensure it works as intended and meets acceptance criteria.
- [x] Release the feature to users.

Size: L

**Comment by CJAkkuec** [comment]
> As a user
> I want to view more information about a card and
> easily switch back to the summary view.

I think I'd prefer a somewhat more specific description of the card and its purpose, otherwise this is looking great! 👍 
Maybe it'd be beneficial to add the expected size, though.

**Comment by REFAEI91** [comment]
thank you for your comment , I have chenged what you refer to .

**Comment by CJAkkuec** [comment]
LGTM! 🚀
