### ISSUE TITLE
Add search function to home page

### ISSUE THREAD

**Issue by REFAEI91** [REFAEI91/capstone-project#3]
## Value proposition

As a user
I want to search for specific cards  
## Description

 
![US 3](https://user-images.githubusercontent.com/56527662/236171505-5011c2b4-0e1e-4c2a-9ce8-053a16e9c54c.png)

## Acceptance criteria

- [x]  The search function should be prominently displayed 
    on the top  home page.
- [x] Users should be able to enter a search term and 
    see relevant results.
- [x] The search function should search the titles and 
    descriptions of all cards on the home page.
- [x] The search results should be displayed in a clear 
    and organized manner.
- [x] The search function should be fast and responsive.

## Tasks

- [x] Design the user interface for the search function on the home page.
- [x] Implement the search functionality to search the titles and descriptions of all cards on the home page.
- [x] Display the search results in a clear and organized manner.
- [x] Test the feature to ensure it works as intended and meets acceptance criteria.
- [x] Release the feature to users.

Size: L

**Comment by CJAkkuec** [comment]
>  The user can go back easly to the Homepage

As far as I can tell, the search function is happening on the Homepage anyway, I think? I don't think you need a back button, you only need to implement the search feature correctly, so that deleting the search term reverts to the complete list. You'd be staying on the Homepage since no routing is necessary.
