### ISSUE TITLE
  Add bookmark button to cards

### ISSUE THREAD

**Issue by REFAEI91** [REFAEI91/capstone-project#4]
## Value proposition

As a user
I want to save cards to my Bookmarks page
by clicking a button on the top right of card. 

## Description

![US 4](https://user-images.githubusercontent.com/56527662/236154684-9fca5c23-0c58-4291-ae9f-06059208a542.png)

## Acceptance criteria

- [x] Each card should have a bookmark button that toggles the color of the bookmark button between black and red.
- [x] When the user clicks the bookmark button, the color of the  bookmark button should change to red, indicating that it has been bookmarked.
- [x] When the user clicks the bookmark button again,  the color of the  bookmark button should change back to black, indicating that the card has been un-bookmarked.
- [x] The bookmark status of each card should be  saved and persist across sessions.
## Tasks

- [x] Design the user interface for the bookmark button
     on each card.
- [x] Implement the functionality to toggle the color of the bookmark button when the bookmark button is clicked.
- [x] Implement the functionality to save the bookmark status of each card in the user's profile.
- [x] Test the feature to ensure it works as intended and meets acceptance criteria.
- [x] Release the feature to users.

Size: L

**Comment by CJAkkuec** [comment]
> Each card should have a bookmark button that toggles the color of the card between black and red.
 
> Implement the functionality to toggle the color of the card when the bookmark button is clicked.

I know this is a little nit-picky, but are you sure you mean to say that the color of the entire card will change? In the strictest sense of the word, if you meant to toggle the color of the bookmark but the acceptance criteria speaks of the card itself, this would be a failed acceptance criteria once the feature would reach QA. 🤯

**Comment by REFAEI91** [comment]
Sorry that was a mistake , I mean color of bookmark button not the entier card . i have already corrected👍🏻

**Comment by HenrikeStahlhut** [comment]
LGTM after your edits 🏋🏻‍♀️
