### ISSUE TITLE
Display all bookmarked cards on bookmarks page

### ISSUE THREAD

**Issue by REFAEI91** [REFAEI91/capstone-project#5]
## Value proposition

As a user, I want a bookmarks page that displays all of my bookmarked cards so that I can easily access and review them at any time without having to search through the entire platform.

## Description
![US 5](https://user-images.githubusercontent.com/56527662/236159726-78d762e1-d3d2-44a4-8c9f-8843eec1f74c.png)

## Acceptance criteria

- [x] The bookmarks page should display a list of all the user's bookmarked cards.
- [x] Each bookmarked card should display its title, and a brief summary.
- [x] The bookmarks page should display a message if there are no bookmarks saved.
- [x] The user can switch easly between Homepage and bookmarks page

## Tasks

- [x] Design the user interface for the bookmarks page.
- [x] Implement the functionality to retrieve the user's bookmarked cards from bookmarks page .
- [x] Display the retrieved bookmarked cards on the bookmarks page.
- [x] Implement the functionality to navigate to the home page when a bookmarked card is clicked.
- [x] Test the feature to ensure it works as intended and meets acceptance criteria.
- [x] Release the feature to users.

Size: L

**Comment by mzschunke** [comment]
Hi Refa, very well written User story! 

Just one tiny thing that I've noticed: I think you're missing the "benefit" part of the value proposition: 

As an <actor>
I want a <feature>
**So that <benefit>**

Sorry for nit-picking :P

**Comment by REFAEI91** [comment]
Thank you for your feedback , I have already  change it 🤓🥳

**Comment by mbosselmann** [comment]
Hi Refaei,
LGTM! 🦊 Your user story will be approved.
