### ISSUE TITLE
Add option to choose whether medication plan is for the user or a family member

### ISSUE THREAD

**Issue by REFAEI91** [REFAEI91/capstone-project#7]
## Value proposition

As a user, I want to be able Add medication plan  for me and for other users to manage medications Plans.

## Description

![US 6 update](https://user-images.githubusercontent.com/56527662/237050287-6d3095aa-12d3-44ee-a02a-7203c6a69fa1.png)

## Acceptance criteria

- [x] Design the user interface for the option to choose whether the medication plan is for the user or for others
- [x] If the user chooses to create a medication plan for others , they should be prompted to enter the other's name and other relevant information.
- [x] The medication plan form should have clear instructions on how to add and manage medications.
- [x] The form should require users to provide the medication name, dosage, frequency, start and end dates, and any other relevant information.
- [ ] Users should be able to track their progress.
- [ ] The medication plan form should be accessible from the home page and clearly labeled.

## Tasks

- [ ]  Design the user interface for the option to choose whether the medication plan is for the user or a somebody else .
- [ ]  Implement the functionality to capture user input for the other's name and other relevant information if the user choose to create a medication plan for a family member.
- [ ] Implement the form functionality to capture user input and validate required fields
- [ ]  Test the feature to ensure it works as intended and meets acceptance criteria.
- [ ]  Release the feature to users.

Size: M

**Comment by HenrikeStahlhut** [comment]
One question: your feature is for adding a new medication plan and choosing wether it's for me or one of my family members, right? 
If that's the case, maybe you could clarify that :) Otherwise looks good.

**Comment by REFAEI91** [comment]
Yes, that's correct. The feature is for adding a new medication plan and allowing the user to choose whether it's for themselves or one of their family members. However, this particular feature is not yet completed. It will be completed in the next user story. Thank you for asking for clarification!

**Comment by Roland-Hufnagel** [comment]
Hi Rafaei, your userstory is clear and detailed. That's fine. Just a few points:
- Since the acceptance-criteria 3 says "... and create a medication plan " this part should be shown in the wireframe.
- I am wondering:  Is your create-form at the 'bookmark-page'? Because this is highlighted in the wireframe.
- I recommend to work with minimal basic data for the moment. E.g. name, age, gender. You can blow it up later with additional data like 'send remainder' and more... (Keep it simple)
- Is it only for family-members? Why? You can use it for 'other people' as well. 
One last question:  Is there a good reason to choose between the user itself and other people? I think the datastructure / medication plans etc. will be similar.

**Comment by REFAEI91** [comment]
Thank you for your feedback , i will update the user story and make all changes

**Comment by frank12421** [comment]
Hi Refaei, great App. LGTM. 👍

**Comment by Roland-Hufnagel** [comment]
Hey! This looks very good now. 💪
You don't like it simple, do you? 😀
Happy Hacking!

**Comment by REFAEI91** [comment]
Sorry, I didn't see it until now. Actually, I do like things a bit complex😂The more complex the problem, the more fun it is to solve! But I also understand the importance of keeping things simple and user-friendly. @Roland-Hufnagel
